"use strict";

const fibonacci = () => {
  // Find fibonacci numbers until is surpasses 350
  let numbers = [0, 1];
  for (let i = 1, temp = 0; temp < 350; i++) {
    temp = numbers[i - 1] + numbers[i];
    numbers.push(temp);
  }
  return numbers;
};

// Check is num is inside array generated by fibonacci func above
const isFibonnaci = (num) => fibonacci().includes(num);
module.exports = {
  fibonacci,
  isFibonnaci,
};
